version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mind_tracker
    environment:
      POSTGRES_USER: bala
      POSTGRES_PASSWORD : bala@1234
      POSTGRES_DB: mindTracker


    ports:
        - "5432:5432"

    volumes:
      - mindTracker:/var/lib/postgresql/data



volumes:
  mindTracker_data: